### ISSUE TITLE
Inefficient SpinLock implementation

### ISSUE THREAD

**Issue by anton-malakhov** [bloomberg/quantum#123]
**Describe the bug**
SpinLock as it is implemented in Quantum kills neighbor HyperThread performance and consumes excessive power.

**Proposal**
Use PAUSE instruction (`_mm_pause();` intrinsic) for short-duration lock. Use a back-off algorithm to gradually reduce bus traffic used for the atomic checks. Insert co-op yield point if it takes too long to acquire the lock.

**Additional context**
* The subject refers to this code: https://github.com/bloomberg/quantum/blob/master/quantum/impl/quantum_spinlock_impl.h#L33
* Please refer to this blog:
https://software.intel.com/en-us/articles/long-duration-spin-wait-loops-on-hyper-threading-technology-enabled-intel-processors and Intel Optimization Manual

**Comment by accelerated** [comment]
Hi @anton-malakhov, yes the current implementation is rather simplistic. Given enough time I will look into this. However would you like to propose a PR instead?
