### ISSUE TITLE
wiki images broken

### ISSUE THREAD

**Issue by park53kr** [bloomberg/quantum#70]
Hi. Thank you for creating a nice coroutine library!

I found that the images in the wiki were broken. 

I think the images such as overall architecture are quite informative so it should be back!

[the commit](https://github.com/bloomberg/quantum/commit/35826922a8c939ac42ef197f7c64a6ccba61e9b6?short_path=c13b55d#diff-c13b55d095ef1152f92f4336fdc57997) made the images broken.

**Comment by accelerated** [comment]
Fixed! thanks for noticing.
